[package]
name = "cookies"
version = "0.1.0"
edition = "2024"

[dependencies]
rs-firebase-admin-sdk = { path = "../../lib" }
time = { version = "0.3" }
tokio = { version = "1.49", features = ["macros", "rt-multi-thread"] }