[package]
name = "get_users"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-firebase-admin-sdk = { path = "../../lib" }
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }